from tkinter import*
def click(event):
    global x
    text = event.widget.cget("text")
    print(text)
    if text == "=":
        if x.get().isdigit():
            value = int(x.get())
        else:
            value = eval(e1.get())
        x.set(value)
        e1.update()

    elif text == "c":
        x.set("")
        e1.update()

    else:
        x.set(x.get() + text)
        e1.update()
t=Tk()
t.geometry("370x900")
t.title("CALCULATOR")
x=StringVar()
e1=Entry(t,textvariable=x,font="lucida 25 bold")
e1.pack()
f = Frame(t,bg="light blue")
b=Button(f,text="c",padx=19,pady=12,font="lucida 25 bold")
b.pack(side=LEFT,padx=18,pady=12)
b.bind("<Button-1>",click)
#f.pack()
b=Button(f,text="/",padx=19,pady=12,font="lucida 25 bold")
b.pack(side=LEFT,padx=18,pady=12)
b.bind("<Button-1>",click)
#f.pack()
b=Button(f,text="%",padx=19,pady=12,font="lucida 25 bold")
b.pack(side=LEFT,pady=12,padx=18)
b.bind("<Button-1>",click)
f.pack()

f = Frame(t,bg="light blue")
b=Button(f,text="7",padx=20,pady=12,font="lucida 25 bold")
b.pack(side=LEFT,padx=18,pady=12)
b.bind("<Button-1>",click)
#f.pack()
b=Button(f,text="8",padx=20,pady=12,font="lucida 25 bold")
b.pack(side=LEFT,padx=18,pady=12)
b.bind("<Button-1>",click)
#f.pack()
b=Button(f,text="9",padx=20,pady=12,font="lucida 25 bold")
b.pack(side=LEFT,pady=12,padx=18)
b.bind("<Button-1>",click)
f.pack()
f = Frame(t,bg="light blue")
b=Button(f,text="4",padx=20,pady=12,font="lucida 25 bold")
b.pack(side=LEFT,padx=18,pady=12)
b.bind("<Button-1>",click)
#f.pack()
b=Button(f,text="5",padx=20,pady=12,font="lucida 25 bold")
b.pack(side=LEFT,padx=18,pady=12)
b.bind("<Button-1>",click)
#f.pack()
b=Button(f,text="6",padx=20,pady=12,font="lucida 25 bold")
b.pack(side=LEFT,pady=12,padx=18)
b.bind("<Button-1>",click)
f.pack()
f = Frame(t,bg="light blue")
b=Button(f,text="1",padx=20,pady=12,font="lucida 25 bold")
b.pack(side=LEFT,padx=18,pady=12)
b.bind("<Button-1>",click)
#f.pack()
b=Button(f,text="2",padx=20,pady=12,font="lucida 25 bold")
b.pack(side=LEFT,padx=18,pady=12)
b.bind("<Button-1>",click)
#f.pack()
b=Button(f,text="3",padx=20,pady=12,font="lucida 25 bold")
b.pack(side=LEFT,pady=12,padx=18)
b.bind("<Button-1>",click)
f.pack()
f = Frame(t,bg="light blue")
b=Button(f,text="=",padx=21.5,pady=12,font="lucida 25 bold")
b.pack(side=LEFT,padx=18,pady=12)
b.bind("<Button-1>",click)
#f.pack()
b=Button(f,text="0",padx=21.5,pady=12,font="lucida 25 bold")
b.pack(side=LEFT,padx=18,pady=12)
b.bind("<Button-1>",click)
#f.pack()
b=Button(f,text=".",padx=21.5,pady=12,font="lucida 25 bold")
b.pack(side=LEFT,pady=12,padx=21)
b.bind("<Button-1>",click)
f.pack()
f = Frame(t,bg="light blue")
b=Button(f,text="+",padx=23,pady=12,font="lucida 25 bold")
b.pack(side=LEFT,padx=18,pady=12)
b.bind("<Button-1>",click)
#f.pack()
b=Button(f,text="*",padx=24,pady=12,font="lucida 25 bold")
b.pack(side=LEFT,padx=18,pady=12)
b.bind("<Button-1>",click)
#f.pack()
b=Button(f,text="-",padx=24,pady=12,font="lucida 25 bold")
b.pack(side=LEFT,pady=12,padx=18)
b.bind("<Button-1>",click)
f.pack()
#f = Frame(t,bg="light blue")
#b=Button(f,text="+",padx=19,pady=12,font="lucida 25 bold")
#b.pack(side=LEFT,padx=18,pady=12)
#b.bind("<Button-1>",click)
#f.pack()
#b=Button(f,text="=",padx=19,pady=12,font="lucida 25 bold")
#b.pack(side=LEFT,padx=18,pady=12)
#b.bind("<Button-1>",click)
#f.pack()
#b.pack(side=LEFT,pady=12,padx=18)
#b.bind("<Button-1>",click)
#f.pack()

t.mainloop()